name: Scrape and Deploy

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: |
          python scraper.py
          mkdir -p tmp
          mv hockey_schedule.ics tmp/

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push
        run: |
          cp ../tmp/hockey_schedule.ics /tmp/hockey_schedule.ics
          git switch gh-pages || git checkout --orphan gh-pages
          rm -rf *
          mv /tmp/hockey_schedule.ics index.ics
          git add index.ics
          git commit -m "Update calendar" || echo "No changes"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
