name: Daily Scraper

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 6AM UTC
  workflow_dispatch:     # Manual trigger in Actions UI

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit .ics to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git fetch origin gh-pages
          git switch gh-pages || git checkout --orphan gh-pages
          mv hockey_schedule.ics index.ics
          git add index.ics
          git commit -m "Update .ics file" || echo "No changes"
          git push origin gh-pages